const Location = @This();
id: i32,
active: bool,
name: []u8,
phone: []u8,
address_1: []u8,
address_2: []u8,
city: []u8,
state: []u8,
zip_code: []u8,
date_created: []u8,
date_updated: []u8,
created_by: ?[]u8,
updated_by: ?[]u8,
